apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namePrefix: dev-

          #cloud-config
patches:
- patch: |
    - op: replace
      path: /spec/template/spec/volumes/1/cloudInitNoCloud/userData
      value: |-
        package_upgrade: true
        packages:
          - httpd
          - gcc
        runcmd:
          - systemctl enable httpd
          - systemctl start httpd
  target:
    kind: VirtualMachine
resources:
- ../base
